export declare class GdbProxyServer {
    private socketPort;
    private server;
    private socket;
    private targetMac;
    private client;
    private port;
    private pendingExchanges;
    private chain;
    private polling;
    private interruptRequested;
    private registers;
    private targetXmlBuffer;
    private targetXmlComplete;
    private debugPrintListener;
    private inPacket;
    private packetBody;
    private checksumChars;
    private inChecksum;
    constructor(socketPort: number);
    start(): Promise<number>;
    setTarget(mac: string): void;
    onConsoleOutput(handler: (text: string) => void): void;
    detachConsoleOutput(): void;
    dispose(): void;
    private onClient;
    private onClientData;
    private checksum;
    private sendToGdb;
    private onInterrupt;
    private enqueuePacket;
    private handlePacket;
    private accumulateTargetXml;
    private parseRegistersFromXml;
    private readAllRegistersIndividually;
    private isResumePacket;
    private pollForStop;
    private exchange;
    private onReply;
    private makeid;
}
